version: '2'

services:
  php70:
    volumes:
    - web-sync:/data:rw
  php56:
    volumes:
    - web-sync:/data:rw
  php71:
    volumes:
    - web-sync:/data:rw
  php72:
    volumes:
    - web-sync:/data:rw
  web:
    volumes:
    - web-sync:/data:ro
  db:
    volumes:
    - dockerdev-mysql-volume:/var/lib/mysql:rw
volumes:
  web-sync:
    external: true
  dockerdev-mysql-volume:
    external: true